# Download test data from: https://osf.io/8jz7e/
model_path: ./output/pth/Bronchial/0908_140000/epoch_23_niters_159000_bes_0.1373.pth #epoch_18_niters_126000_bes_0.1373.pth  

model:
  name: UNet3D
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 1
  # determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)
  layer_order: gcr
  # initial number of feature maps
  f_maps: [32, 64, 128, 256]
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: true
predictor:
  name: 'THStandardPredictor'

  labels: ["Bronchial"]
  sigmoid_threshold: 0.51 #0.6 #0.55 #

loaders:
  # save predictions to output_dir
  # output_dir: ./output/res/h5/epoch_21_niters_93000_vtk
  # output_dir: ./output/res/h5/0804/debug
  # output_dir: ./output/res/stl/Sphere/0804_162025/oneliner/epoch_21_niters_93000_vtk_96_160
  # output_dir: ./output/res/stl/Sphere/0818_164000/

  output_dir: ./output/res/stl/Bronchial/0908_140000/96_160_80_144  #32_288_16_256 #

  # output_dir: ./output/res/stl/Sphere/0822_140000/
  # batch dimension; if number of GPUs is N > 1, then a batch_size of N * batch_size will automatically be taken for DataParallel
  batch_size: 1
  # how many subprocesses to use for data loading
  num_workers: 8
  # test loaders configuration
  test:
    # file_paths: ["./data/test/"]
    # file_paths: ["/data/dulicui/project/data/data03_h5/test_vtk"]
    # file_paths: ["/data/dulicui/project/data/data03_h5/test_debug/"]
    
    # test_base_path: "/mnt/Data/data_sphere_test/"
    test_base_path: /media/ubuntu/Elements SE/data_sphere_test/
    # test_base_path: /media/ubuntu/Elements SE/data00/dst/dicom/

    slice_builder:
      name: THSliceBuilder
      # patch_shape: [32, 512, 512]
      # stride_shape: [24, 496, 496]
      # patch_shape: [128, 128, 128]
      # stride_shape: [96, 112, 112]
      # patch_shape: [32, 256, 256]
      # stride_shape: [24, 240, 240]

      # patch_shape: [16, 256, 256]
      # stride_shape: [8, 240, 240]

      # patch_shape: [32, 224, 224]
      # stride_shape: [24, 208, 208]

      # 目前再用
      patch_shape: [96, 160, 160]
      stride_shape: [80, 144, 144]

      # stride_shape: [64, 128, 128]
      # stride_shape: [64, 96, 96]
      # stride_shape: [32, 64, 64]
      # stride_shape: [64, 64, 64]
      # stride_shape: [32, 32, 32]

      # patch_shape: [4, 512, 512]
      # stride_shape: [4, 496, 496]

      # patch_shape: [16, 336, 336]
      # stride_shape: [12, 320, 320]
      # stride_shape: [12, 328, 328]
      # stride_shape: [8, 328, 328]

      # patch_shape: [32, 288, 288]
      # # stride_shape: [24, 272, 272]
      # stride_shape: [16, 256, 256]

      # patch_shape: [128, 160, 160]
      # stride_shape: [112, 144, 144]

      # patch_shape: [256, 64, 64]
      # stride_shape: [240, 56, 56]

    transformer:
      raw:
        # - name: Standardize
        - name: THNormalize
          # min_value: -1024
          # max_value: -690  ## wl=-850,ww=310
          min_value: -1005
          max_value: -695  ## wl=-850,ww=310
        - name: ToTensor
          expand_dims: true

    