# Download test data from: https://osf.io/8jz7e/
model_path: ./output/pth/Sphere/0818_164000/epoch_23_niters_111000_bes_0.0499.pth  #epoch_21_niters_99000_bes_0.0496.pth
#""  #"./output/pth/epoch_24_niters_105000_bes_0.5182.pth"
#  #./output/pth/best_checkpoint.pytorch_epoch_8_niters_200_bes_0.064
model:
  name: UNet3D
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 1
  # determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)
  layer_order: gcr
  # initial number of feature maps
  f_maps: [32, 64, 128, 256]
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: true
predictor:
  name: 'THStandardPredictor'
  labels: ["sphere"]
  sigmoid_threshold: 0.6

loaders:
  # save predictions to output_dir
  # output_dir: ./output/res/h5/epoch_21_niters_93000_vtk
  output_dir: ./output/res/stl/Sphere/0818_164000/
  # batch dimension; if number of GPUs is N > 1, then a batch_size of N * batch_size will automatically be taken for DataParallel
  batch_size: 1
  # how many subprocesses to use for data loading
  num_workers: 8
  # test loaders configuration
  test:
    # file_paths: ["./data/test/"]
    # file_paths: ["/data/dulicui/project/data/data03_h5/test_vtk"]
    # file_paths: ["/data/dulicui/project/data/data03_h5/test_debug/"]
    test_base_path: /mnt/Data/data_sphere_test/

    slice_builder:
      name: THSliceBuilder
      # patch_shape: [64, 128, 128]
      # stride_shape: [48, 112, 112]
      patch_shape: [32, 128, 128]
      stride_shape: [24, 112, 112]

    transformer:
      raw:
        - name: Standardize
        - name: ToTensor
          expand_dims: true