# Download test data from: https://osf.io/8jz7e/
# model_path: ./output/pth/Sphere/0804_162025/epoch_21_niters_93000_bes_0.5182.pth  #./output/pth/epoch_26_niters_114000_bes_0.5182.pth
# model_path: ./output/pth/Sphere/0818_164000/epoch_29_niters_132000_bes_0.1235.pth
model_path: ./output/pth/Sphere/0822_140000/epoch_44_niters_201000_bes_0.5182.pth  #epoch_41_niters_183000_bes_0.5182.pth  #epoch_28_niters_120000_bes_0.5182.pth #
# model_path: /data/dulicui/project/git/pytorch-3dunet/output/pth/Sphere/0804_162025/epoch_21_niters_93000_bes_0.5182.pth 
#""  #"./output/pth/epoch_24_niters_105000_bes_0.5182.pth"
#  #./output/pth/best_checkpoint.pytorch_epoch_8_niters_200_bes_0.064
model:
  name: UNet3D
  # number of input channels to the model
  in_channels: 1
  # number of output channels
  out_channels: 1
  # determines the order of operators in a single layer (crg - Conv3d+ReLU+GroupNorm)
  layer_order: gcr
  # initial number of feature maps
  f_maps: [32, 64, 128, 256]
  # number of groups in the groupnorm
  num_groups: 8
  # apply element-wise nn.Sigmoid after the final 1x1x1 convolution, otherwise apply nn.Softmax
  final_sigmoid: true
predictor:
  name: 'THStandardPredictor'

  labels: ["sphere"]
  sigmoid_threshold: 0.6

loaders:
  # save predictions to output_dir
  # output_dir: ./output/res/h5/epoch_21_niters_93000_vtk
  # output_dir: ./output/res/h5/0804/debug
  # output_dir: ./output/res/stl/Sphere/0804_162025/oneliner/epoch_21_niters_93000_vtk_96_160
  # output_dir: ./output/res/stl/Sphere/0818_164000/
  # output_dir: ./output/res/stl/Sphere/0804_162025/oneliner
  output_dir: ./output/res/stl/Sphere/0822_140000/
  # batch dimension; if number of GPUs is N > 1, then a batch_size of N * batch_size will automatically be taken for DataParallel
  batch_size: 1
  # how many subprocesses to use for data loading
  num_workers: 8
  # test loaders configuration
  test:
    # file_paths: ["./data/test/"]
    # file_paths: ["/data/dulicui/project/data/data03_h5/test_vtk"]
    # file_paths: ["/data/dulicui/project/data/data03_h5/test_debug/"]
    test_base_path: "/mnt/Data/data_sphere_test/"

    slice_builder:
      name: THSliceBuilder
      # patch_shape: [32, 512, 512]
      # stride_shape: [24, 496, 496]
      # patch_shape: [128, 128, 128]
      # stride_shape: [112, 112, 112]
      # patch_shape: [32, 256, 256]
      # stride_shape: [24, 240, 240]

      # patch_shape: [16, 256, 256]
      # stride_shape: [8, 240, 240]

      # patch_shape: [32, 224, 224]
      # stride_shape: [24, 208, 208]

      patch_shape: [96, 160, 160]
      stride_shape: [80, 144, 144]
      # patch_shape: [4, 512, 512]
      # stride_shape: [4, 496, 496]

    transformer:
      raw:
        - name: Standardize
        - name: ToTensor
          expand_dims: true

    